package com.exam;
// Generated May 9, 2019 11:42:08 PM by Hibernate Tools 4.3.1



/**
 * Highlights generated by hbm2java
 */
public class Highlights  implements java.io.Serializable {


     private Integer pid;
     private String title;
     private String post;
     private String date;

    public Highlights() {
    }

    public Highlights(String title, String post, String date) {
       this.title = title;
       this.post = post;
       this.date = date;
    }
   
    public Integer getPid() {
        return this.pid;
    }
    
    public void setPid(Integer pid) {
        this.pid = pid;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPost() {
        return this.post;
    }
    
    public void setPost(String post) {
        this.post = post;
    }
    public String getDate() {
        return this.date;
    }
    
    public void setDate(String date) {
        this.date = date;
    }




}


